-- CreateTable
CREATE TABLE `Subscription` (
    `id` VARCHAR(191) NOT NULL,
    `seller_id` VARCHAR(191) NOT NULL,
    `product_id` VARCHAR(191) NOT NULL,
    `product_name` VARCHAR(191) NOT NULL,
    `permalink` VARCHAR(191) NOT NULL,
    `product_permalink` VARCHAR(191) NOT NULL,
    `short_product_id` VARCHAR(191) NOT NULL,
    `email` VARCHAR(191) NOT NULL,
    `price` VARCHAR(191) NOT NULL,
    `gumroad_fee` VARCHAR(191) NOT NULL,
    `currency` VARCHAR(191) NOT NULL,
    `quantity` VARCHAR(191) NOT NULL,
    `discover_fee_charged` VARCHAR(191) NOT NULL,
    `can_contact` VARCHAR(191) NOT NULL,
    `referrer` VARCHAR(191) NOT NULL,
    `card` JSON NOT NULL,
    `order_number` VARCHAR(191) NOT NULL,
    `sale_id` VARCHAR(191) NOT NULL,
    `sale_timestamp` VARCHAR(191) NOT NULL,
    `purchaser_id` VARCHAR(191) NOT NULL,
    `subscription_id` VARCHAR(191) NOT NULL,
    `url_params` JSON NOT NULL,
    `variants` JSON NOT NULL,
    `test` VARCHAR(191) NOT NULL,
    `ip_country` VARCHAR(191) NOT NULL,
    `recurrence` VARCHAR(191) NOT NULL,
    `is_gift_receiver_purchase` VARCHAR(191) NOT NULL,
    `refunded` VARCHAR(191) NOT NULL,
    `resource_name` VARCHAR(191) NOT NULL,
    `disputed` VARCHAR(191) NOT NULL,
    `dispute_won` VARCHAR(191) NOT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
